import viteLogo from "/queen.png";

export const mockdata = [
  {
    id: 1,
    name: "iPhone 20 Max Pro",
    description: "Full Paid po ito",
    category: "MB",
    date_found: "2025-03-11",
    time_found: "13:51:21",
    location_found: "East Wing Laboratory",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 2,
    name: "Leather wallet",
    description: "May lamang national ID, ATM, and konting cash",
    category: "WT",
    date_found: "2025-03-12",
    time_found: "13:51:21",
    location_found: "East Wing Laboratory",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 3,
    name: "Eco bag",
    description: "May lamang notebook, ballpen, tapos kit",
    category: "BA",
    date_found: "2025-03-14",
    time_found: "13:51:21",
    location_found: "Library",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 4,
    name: "Motor Key",
    description: "Motor key nakita ko sa parking ng PUP sa may oval",
    category: "KY",
    date_found: "2025-03-17",
    time_found: "10:49:18",
    location_found: "Oval",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 5,
    name: "smartphone",
    description: "Black Samsung Galaxy found near the Main Library charging station",
    category: "MB",
    date_found: "2025-03-19",
    time_found: "14:30:08",
    location_found: "PUP Main Library",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 6,
    name: "Student ID",
    description: "PUP Student ID with name Franchesca Miranda found at CEA Building",
    category: "ID",
    date_found: "2025-03-20",
    time_found: "09:15:00",
    location_found: "PUP CEA Building",
    photo_url: viteLogo,
    status: "CL",
  },
  {
    id: 7,
    name: "Umbrella",
    description: "Blue folding umbrella left at the lagoon",
    category: "MS",
    date_found: "2025-03-20",
    time_found: "12:45:00",
    location_found: "PUP Lagoon",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 8,
    name: "Yellow notebook",
    description: "Yellow notebook with IT notes found at South Wing 5th floor",
    category: "MS",
    date_found: "2025-03-22",
    time_found: "10:12:13",
    location_found: "South Wing 5th Floor",
    photo_url: viteLogo,
    status: "CL",
  },
  {
    id: 9,
    name: "Thesis Document",
    description: "Research proposals ng BSCS 3-5 para sa COSC 304",
    category: "MS",
    date_found: "2025-03-24",
    time_found: "14:23:25",
    location_found: "Near S512",
    photo_url: viteLogo,
    status: "CL",
  },
  {
    id: 10,
    name: "Income Taxation Book",
    description: "Book by Tabag and Garcia",
    category: "MS",
    date_found: "2025-03-25",
    time_found: "11:36:27",
    location_found: "Near Souvenir Shop",
    photo_url: viteLogo,
    status: "UC",
  },
  {
    id: 11,
    name: "Scientific Calculator",
    description: "Casio fx-991ES model",
    category: "EL",
    date_found: "2025-03-25",
    time_found: "16:34:09",
    location_found: "Engineering Building 4th floor",
    photo_url: viteLogo,
    status: "UC",
  }
];
